### ISSUE TITLE
build iOS fail 

### ISSUE THREAD

**Issue by lwglwg** [getnamo/socketio-client-unreal#127]
UATHelper: Packaging (iOS):   /Users/wengangli/Downloads/luoyazhanji/Game/Plugins/socketio-client-ue4-master/Source/CoreUtility/Private/CoreUtilityBPLibrary.cpp:16:9: error: unknown pragma ignored [-Werror,-Wunknown-pragmas]
UATHelper: Packaging (iOS):   #pragma warning( push )
UATHelper: Packaging (iOS):           ^
UATHelper: Packaging (iOS):   /Users/wengangli/Downloads/luoyazhanji/Game/Plugins/socketio-client-ue4-master/Source/CoreUtility/Private/CoreUtilityBPLibrary.cpp:17:9: error: unknown pragma ignored [-Werror,-Wunknown-pragmas]
UATHelper: Packaging (iOS):   #pragma warning( disable : 5046)
UATHelper: Packaging (iOS):           ^
UATHelper: Packaging (iOS):   /Users/wengangli/Downloads/luoyazhanji/Game/Plugins/socketio-client-ue4-master/Source/CoreUtility/Private/CoreUtilityBPLibrary.cpp:222:9: error: unknown pragma ignored [-Werror,-Wunknown-pragmas]
UATHelper: Packaging (iOS):   #pragma warning( pop )
UATHelper: Packaging (iOS):           ^
PackagingResults: Error: unknown pragma ignored [-Werror,-Wunknown-pragmas]
PackagingResults: Error: unknown pragma ignored [-Werror,-Wunknown-pragmas]
PackagingResults: Error: unknown pragma ignored [-Werror,-Wunknown-pragmas]

**Comment by getnamo** [comment]
see https://github.com/catchorg/Catch2/issues/280 update your clang compiler or run command with ```-Wno-unknown-pragmas```

**Comment by getnamo** [comment]
I don't have this platform myself, will require help from other iOS devs to replicate this issue.

**Comment by getnamo** [comment]
Closing due to age, re-open if problem persists in new plugin versions.
