### ISSUE TITLE
multiplayer game with socketio

### ISSUE THREAD

**Issue by Sere1** [getnamo/socketio-client-unreal#185]
Hi i want to create a multiplayer game with using sio.  I'm using listen server. Can i use replication? How will clients see each other?

**Comment by getnamo** [comment]
Socket.io is just an event based data pipeline with json/binary support. It doesn't support automatic replication as you think of it in Unreal. Unreal's native networking does quite a bit of heavy lifting to allow you to simply use a tick box on a UProperty in an actor to replicate that property across to other clients. It is quite efficient and the recommended route to do multiplayer networking if recompiling a server build for every network change isn't prohibitive in your context.

That said if you wanted to specifically use socket.io for networking in a multiplayer game you could use something like an 'echo' server on the node.js side

```javascript
const app = require('express')();
const http = require('http').Server(app);
const io = require('socket.io')(http);
...
io.on('connection', (socket) =>{
	...
	socket.on('replicate', (data)=>{
		console.dir(data, { depth:null});	//only for debug output
		socket.broadcast.emit('onReplicatedData', data);
	});
	...
}
```

This server will simply re-broadcast a message it got from a client to all other clients as an ```onReplicatedData``` event. 

Keep in mind that unlike Unreal's replication, there isn't a directly authoritative way to check values for e.g. cheating prevention. To do that you'd need to check data sent/received in the clients or add some validation logic on the server (which may be difficult for e.g. physics simulations that require a full unreal logic, but not impossible).

If however cheating isn't a concern for your use case, then an echo server is the simplest type of server that can satisfy networking and you can just focus on routing the data on the client side.

Let's say you have a pawn and you want to replicate its location to other clients. First as a client you'd need to emit some kind of event that specifies that a new pawn has joined (e.g. a new player event), the other clients should then receive something like ```onPlayerJoined``` and would spawn a pawn. The *SocketIOClientComponent* receiving this would probably be a unique actor/game instance that would handle all the replication messages, routing based on an ID. So the ```onPlayerJoined``` event should provide some unique ID to keep track of it and it should also be emitted back to the sending player so they know what ID to add to their messages.

```javascript
...
	socket.on('newPlayer', (playerStartupData, callback)=>{
		//Get a unique id (socket.id is long but unique, suitable for player id)
		//can optionally use any other unique id system.
		const playerId = socket.id;  
		console.log('newPlayer joined: ' + socket.id);
		
		//let the sending player know their id via callback
		callback(playerId);
		
		//add id to startup data and tell other players about this player
		playerStartupData.id = playerId;
		socket.broadcast.emit('onPlayerJoined', playerStartupData);
	});
...
```

Then from the sending client you would emit e.g. a position and rotation of your pawn (either every tick or when the value changed) to the replication event with the id wrapper

```json
{
	"id":"1",
	"position":{"x":10,"y":10,"z":0},
	"rotation":{"x":0,"y":90,"z":0}
}
```

and on the receiving side you would receive the ```onReplicatedData``` and you'd update the pawn with the id with the received location data (ideally using an interface to keep things clean and consistent).

And that is it. You can extend this logic to cover other types of actors e.g. let's say a flying bullet: You'd similarly emit an event to let the other clients know about the spawned bullet e.g. ```newActor``` along with some unique ID and type specifier from the owning client and the other clients would spawn it using e.g. ```onNewActor``` and then update it with your ```onReplicatedData``` with your unique ID (along with a delete event eventually). 

Keep in mind that some optimizations should be used to make this work well: 
- using an ID=>actor map to quickly lookup where to route your data to in the clients
- possibly serializing or compressing the data
- reducing emit rates to keep the bandwidth in check. 

Also you could try a different architecture with e.g. a *SocketIOClientComponent* per object, but this will have more overhead. If you're having problems routing internally, consider using a global event system https://github.com/getnamo/global-event-system-ue4

**Comment by Sere1** [comment]
`gameInstance->Sockett->OnEvent(TEXT("new_user"), [this](const FString& Event, const TSharedPtr<FJsonValue>& Message)
		{
			if (ActorToSpawn)
			{
				TSharedPtr<FJsonObject> JsonObject = MakeShareable(new FJsonObject);
				JsonObject = Message->AsObject();
				FString id1 = JsonObject->GetStringField(FString("name"));

				float x = JsonObject->GetNumberField("x");
				float y = JsonObject->GetNumberField("y");
				float z = JsonObject->GetNumberField("z");
				float rX = JsonObject->GetNumberField("rx");
				float rY = JsonObject->GetNumberField("ry");
				float rZ = JsonObject->GetNumberField("rz");

				UWorld* WRLD = GetWorld();
				JsonObject = Message->AsObject();
				FName name = FName(*id1);
				FActorSpawnParameters spawnParams;
				spawnParams.Owner = this;
				spawnParams.Name = name;
				spawnParams.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AdjustIfPossibleButAlwaysSpawn;
				FRotator rotater;
				FVector spawnLocation = FVector(-19, 603, 534);
			
				if(id1 != insName)
				{
					WRLD->SpawnActor<AMyActor>(ActorToSpawn, spawnLocation, rotater, spawnParams);
					GEngine->AddOnScreenDebugMessage(-1, 15.0f, FColor::Yellow, (TEXT("%s"), *USIOJConvert::ToJsonString(Message)));
				}
			}		
		});` 
Okey. I thought like you said.  On unreal side, i'm spawning a actor like this for other client characters. Is it true? And i'm not making progress on unreal side. You said that let's say a flying bullet: I can emit an event but I can't go to the next step. I'm having a hard time with unreal side.

**Comment by tgienger** [comment]
I'm exploring options to allow server to server replication of sorts. The thought is to have the servers handle replication as usual for their own clients, but to also send their information to the other unreal servers.

An example would be to have a master server, or distributor server. When game server-1 starts it registers with the distributor sort of like a client and when new server-2 spins up it does the same and with as many servers as necessary. When the first 100 clients connect they connect to server-1, the next 100 clients would connect to server-2 and so on. When client1 performs an action server-1 works just like normal validating and replicating to the other clients connected to server-1 (exactly as it does now), but it also send that same info to the distributor which distributes that data to all of the other connected servers. 
Since this is server to server communication we can trust that it is valid and accept it, sending that data to each of their clients. Assuming proper relevancy of course.

Anyone tried something like this with this plugin before? Any clues where to begin?

**Comment by tgienger** [comment]
In theory I guess when a client connects server1 could send a signal and each responding server could create a clone on their own servers. changes would be end from server1 and applied to the clone, then replication sent to each client.

This would split logic up between different servers allowing for more processing power.

**Comment by getnamo** [comment]
The tricky part would be to inject and listen to unreal server traffic and to replicate it across using socket.io. There are so many unknowns in terms of how to properly capture and then on the other server re-emit it in an unreal fashion.

If you're doing networking purely via socket.io though it would be pretty doable to do the logic split you're thinking of. A *non*-optimal implementation of socket.io replication can be found here: https://github.com/getnamo/sionetworking-unreal
