### ISSUE TITLE
Connect to Python server (Flask)

### ISSUE THREAD

**Issue by KhalidAtawy** [getnamo/socketio-client-unreal#187]
I'm trying to connect to the server side that's being developed with Flask, but it keeps failing to connect with Error number 400.

on the other side its working with the nodejs socket.

any comment about that issue please?

_Addition from issue 120 (copied by @getnamo)_:

```python
from flask import Flask, render_template, request
from flask_socketio import SocketIO, emit

app = Flask(name)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app)

@app.route('/')
def index():
    return render_template('index.html')

@socketio.on('chat message')
def handle_my_custom_event(json):
    print(request.sid)
    print('received json: ' + str(json))
    emit('chat message', json, broadcast=True)

@socketio.on('connect')
def handle_my_custom_event():
    print(request.sid)
    print('received json: Connected')

if name == 'main':
socketio.run(app)
```

and I'm receiving this error when trying to connect.
    
a27a567328004664844b6c6ce5088eb4 received json: Connected 127.0.0.1 - - [06/Feb/2020 11:00:53] "GET /socket.io/?EIO=4&transport=websocket&t=1580979653 HTTP/1.1" 400 -

Any help would be appreciated

**Comment by getnamo** [comment]
See this issue: https://github.com/getnamo/socketio-client-ue4/issues/120

**Comment by getnamo** [comment]
While this is not a flask config, there is a working socket.io server example found here: https://github.com/getnamo/ml-remote-server/blob/master/server.py

**Comment by getnamo** [comment]
Closing due to age, re-open if problem persists in new plugin versions.
