### ISSUE TITLE
Add Support for Rooms

### ISSUE THREAD

**Issue by ughstudios** [getnamo/socketio-client-unreal#199]
https://socket.io/docs/rooms-and-namespaces/

Does this have support for rooms? I know you have namespaces, but not rooms?

**Comment by getnamo** [comment]
Rooms are a server feature, has nothing to do with the client.

**Comment by getnamo** [comment]
There is this section on rooms in the readme: https://github.com/getnamo/socketio-client-ue4/blob/master/README.md#rooms
