### ISSUE TITLE
Stops reconnecting after second attempt 

### ISSUE THREAD

**Issue by staskjs** [getnamo/socketio-client-unreal#201]
Hi,

I am using UE 4.24.3, socket.io plugin version 1.3.10

After a successful connection to server, I stop server and expect client to try reconnecting infinitely, because Max Reconnection Attempts is -1, Reconnection Timeout is 0 and Reconnection Delay is 2000. But attempts stop after second one and client never connects again, even if I start server again. OnConnectionProblems is not called.

However if server isn't started initially, then client tries to reconnect infinitely.

So this problem only visible after an initial successful connect.

**Comment by getnamo** [comment]
Closing due to age, re-open if problem persists in new plugin versions.
