### ISSUE TITLE
C++ Bind to OnConnected / OnDisconnected SocketIOClientComponent Events

### ISSUE THREAD

**Issue by finger563** [getnamo/socketio-client-unreal#217]
I'm trying to bind to these events, though for some reason they seem to only work once - e.g. if I bind `OnConnected` with this code:
```c++
  clientComponent->OnConnected.AddDynamic(this, &ARemoteDisplayActor::OnClientConnected);
```

Then that function only gets called on the first connection, not on any subsequent connections (e.g. reconnections to the same server or connections to different servers). Am I not doing something properly / why is this only getting called on the first connection?

**Comment by finger563** [comment]
Actually it appears that even if i bind to it from blueprints, the connect event is only called the first time and the disconnect event is never called.

**Comment by getnamo** [comment]
That appears to be a bug. You might have more luck with namespace connect/disconnect. Keep in mind that socket.io will generally not emit a disconnect for connection problems as it tries to reconnect an infinite number of times by default (see on connection problems event instead). This might be the behaviour you're seeing. Only clean disconnects would be counted as such.

**Comment by finger563** [comment]
Yea I tried namespace connect / disconnect and had the same issue. I'm actually calling `Disconnect()` myself and then hoping that it will trigger the event when it is disconnected - similarly, after that I manually connect again but I don't see the `Connected` event - this happens with both the `USocketIOClientComponent` and the `FSocketIONative` object.

**Comment by finger563** [comment]
Looking through the SocketIONative.cpp code, it looks like if you manually disconnect, then it removes all callbacks - hence why I'm not seeing any callbacks after the first connection... I can fix that by simply re-binding all callbacks after a disconnect, though it would be nice to have that as an option. If you're open to that I can submit a PR for it.

**Comment by finger563** [comment]
(relatedly, if you call `Disconnect()` then the `OnNamespaceDisconnect` callback is not called, though the `OnDisconnect` callback is)

**Comment by getnamo** [comment]
Closing due to age, re-open if problem persists in new plugin versions.
