### ISSUE TITLE
Disconnect doesn't work?

### ISSUE THREAD

**Issue by brittanft** [getnamo/socketio-client-unreal#220]
I'm constructing the socket component on my GameInstance.

I can only disconnect by unsetting the component value and garbage collecting or by exiting the game client. Calling SocketIOComponent->Disconnect doesn't appear to actually close the connection

**Comment by getnamo** [comment]
Platform & example call (either code calls or bp screenshots)?

**Comment by ouyang-yuxuan** [comment]
![image](https://user-images.githubusercontent.com/36830421/92613820-f502e500-f2ed-11ea-85f7-79b559cb1b91.png)
I have the same problem
Disconnect does not work

**Comment by ouyang-yuxuan** [comment]
> ![image](https://user-images.githubusercontent.com/36830421/92613820-f502e500-f2ed-11ea-85f7-79b559cb1b91.png)
> I have the same problem
> Disconnect does not work

Today it turns out that not only does client disconnect not work, but the server goes offline,OnDisconnect on the client doesn't work, either.java Netty-socketio for the server

**Comment by Darkloud91** [comment]
same prolem here.
