### ISSUE TITLE
 After upgrading from 4.22 to 4.25, it stopped working (Apply URL)

### ISSUE THREAD

**Issue by Shkiper83** [getnamo/socketio-client-unreal#227]
Result 0

**Comment by Shkiper83** [comment]
There is a server on node.js and a database, after authorization I get a zero result.

**Comment by Shkiper83** [comment]
![1](https://user-images.githubusercontent.com/47493808/92240274-03539a00-eec5-11ea-8fc5-efd347ab2563.png)

**Comment by getnamo** [comment]
I'm not sure what if anything changed for this API during those versions. Do you have an example endpoint/project that will repro this?

**Comment by getnamo** [comment]
Try diffing the two source tags and see if https://github.com/getnamo/socketio-client-ue4/blob/15571f939b8173bb89cfac402d7c1962c112d356/Source/SIOJson/Private/SIOJRequestJSON.cpp#L204 changed in a meaningful way.

**Comment by Shkiper83** [comment]
![2](https://user-images.githubusercontent.com/47493808/92261996-1ffeca80-eee3-11ea-881f-19c5e0ea5cc1.png)

**Comment by Shkiper83** [comment]
![3](https://user-images.githubusercontent.com/47493808/92263095-c0a1ba00-eee4-11ea-8dc6-8156cc7cf0da.png)
![4](https://user-images.githubusercontent.com/47493808/92263099-c13a5080-eee4-11ea-932b-cb2634d40356.png)

**Comment by getnamo** [comment]
One diff between https://github.com/getnamo/socketio-client-ue4/blob/v1.1.0/Source/SIOJson/Private/SIOJRequestJSON.cpp and https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SIOJson/Private/SIOJRequestJSON.cpp is the addition of ```bShouldHaveBinaryResponse```, try emitting with it equal to true/false to see if it makes any difference. Default should be false. If that doesn't solve it, something changed deeper, possibly engine change

**Comment by Shkiper83** [comment]
An exception was thrown at 0x00007FFE3C30AE7E (UE4Editor-SIOJson.dll) in UE4Editor.exe: 0xC0000005: A read access violation at 0x0000000000000030. Occurred
![4](https://user-images.githubusercontent.com/47493808/92531387-d7267900-f236-11ea-8003-8d000eae57d8.png)

**Comment by Shkiper83** [comment]
Launched through the debugger in visual studio, it crashes at this point, this is the engine library, USIOJlibrary.

**Comment by getnamo** [comment]
Do you have the .dmp file generated from that crash (found in saved)

**Comment by Shkiper83** [comment]
for some reason it does not create it, in the project in 4.22 it is

**Comment by Shkiper83** [comment]
Here's what I found
![5](https://user-images.githubusercontent.com/47493808/92599664-3f1aa500-f2b3-11ea-8dbf-a6ef77fc22c7.png)

**Comment by Shkiper83** [comment]
I understand that the conversion does not work

**Comment by getnamo** [comment]
Closing due to age, re-open if problem persists in new plugin versions.
