### ISSUE TITLE
Cannot open file "SockerIOClient.h" on rebuild

### ISSUE THREAD

**Issue by oslindstrm** [getnamo/socketio-client-unreal#237]
Trying to build using the Native Socket. Compiling works fine, but on rebuild I get these errors: `Cannot open file "SockerIOClient.h"` & `Cannot open file "SockerIONative.h"`.

 Have declared the modules in my build file as follows: 

`PublicDependencyModuleNames.AddRange(new string[] { "Core", "CoreUObject", "Engine", "InputCore", "HeadMountedDisplay", "HTTP", "SocketIOClient", "SocketIOLib", "Json", "JsonUtilities", "SIOJson" });`

The reason I am trying to rebuild is because when I try and Connect to the remote server via the socket, nothing happens. And I mean nothing. Verbose logging is on but nothing is coming through. I suspect both issues are related.

This is what the connection code looks like: 

```
        Socket = ISocketIOClientModule::Get().NewValidNativePointer();

	TSharedPtr<FJsonObject> QueryParams = MakeShareable(new FJsonObject);
	QueryParams->SetStringField("token", TokenForPlay);

	Socket->VerboseLog = true;
	Socket->Connect(FString(Base_URL + "/Play"), QueryParams, nullptr);

	Socket->OnConnectedCallback = [this](const FString& InSessionId)
	{
		if (GEngine)
		{
			GEngine->AddOnScreenDebugMessage(-10, 5.f, FColor::Green, "Connected");
		}
	};
```

Am I not following the setup guide properly, or is the process for setting up the Native Client different?

**Comment by getnamo** [comment]
At a glance that looks correct, have you added enabled the plugin/added it to the uplugin file and recompiled the project? Its possible the compiler may not see it otherwise

**Comment by getnamo** [comment]
Closing due to age
