### ISSUE TITLE
SocketIO vaRest Send utf-8（Chinese） into question mark

### ISSUE THREAD

**Issue by ouyang-yuxuan** [getnamo/socketio-client-unreal#239]
![image](https://user-images.githubusercontent.com/36830421/95943482-8945f780-0e18-11eb-8332-2441de4a60ae.png)
![image](https://user-images.githubusercontent.com/36830421/95943572-ce6a2980-0e18-11eb-9ee3-bd2b5af316dd.png)

**Comment by getnamo** [comment]
Try sending the data back to unreal and see if characters show correctly. Utf-8 should be fully supported (at least as tested in sio protocol), if not it's likely the way a post request gets encoded which would be a bug

**Comment by ouyang-yuxuan** [comment]
> Try sending the data back to unreal and see if characters show correctly. Utf-8 should be fully supported (at least as tested in sio protocol), if not it's likely the way a post request gets encoded which would be a bug

ue4 varest request
![image](https://user-images.githubusercontent.com/36830421/96945800-46b7a580-1511-11eb-954e-56057396d18f.png)

server callback
![image](https://user-images.githubusercontent.com/36830421/96945781-369fc600-1511-11eb-9cea-966e30d026d2.png)

![image](https://user-images.githubusercontent.com/36830421/96945830-5931df00-1511-11eb-8558-297c9dec7d40.png)
ue4 print

callback character normal

**Comment by Xinyu416** [comment]
I have the same problem and look forward to a solution

**Comment by getnamo** [comment]
Closing due to age, re-open if problem persists in new plugin versions.
