### ISSUE TITLE
varest How to construct an array request

### ISSUE THREAD

**Issue by ouyang-yuxuan** [getnamo/socketio-client-unreal#241]
postman Examples
![image](https://user-images.githubusercontent.com/36830421/97583225-a6daaa00-1a31-11eb-830e-b8ee9bd85394.png)

ue4
1：You can only receive one
![image](https://user-images.githubusercontent.com/36830421/97583417-e608fb00-1a31-11eb-9b78-4fa1a6715bf4.png)
2：ue4 crash
![image](https://user-images.githubusercontent.com/36830421/97583723-3718ef00-1a32-11eb-938d-dc4eeb855a85.png)
3：cant use
![image](https://user-images.githubusercontent.com/36830421/97584174-b4dcfa80-1a32-11eb-9df3-3359315ddbc4.png)
4：none
![image](https://user-images.githubusercontent.com/36830421/97586444-3c2b6d80-1a35-11eb-9c18-8e971430c9a1.png)
![image](https://user-images.githubusercontent.com/36830421/97586295-0f775600-1a35-11eb-9337-828d2c2c4292.png)

**Comment by getnamo** [comment]
I haven't tried an array post myself, but try making an SIOJsonObject that contains an SIOJsonArrayValue, e.g. {'myarray':[1,2,3]} and posting that

**Comment by ouyang-yuxuan** [comment]
> I haven't tried an array post myself, but try making an SIOJsonObject that contains an SIOJsonArrayValue, e.g. {'myarray':[1,2,3]} and posting that

Which node is used, can it be used normally?Please send a screenshot if possible.Thank you very much.
