### ISSUE TITLE
Mac M1 connection issues - (was socket.io lib version mismatch)

### ISSUE THREAD

**Issue by getnamo** [getnamo/socketio-client-unreal#266]
From marketplace questions: 
BNC - _"I am using your example on a Mac M1, and the socket server on an ubuntu machine in the cloud.
The socket server code works correctly via Safari.
If I use your Ue4 app (preview or play in Editor), nothing happens. No error message, but no connection message either."_

**Comment by bcanick** [comment]
Downgraded to socket 2.4.1 and it worked (was on 4.1.2)
 
Waiting for plugin 1.6 to be available on Marketplace
