### ISSUE TITLE
Unreal 5 Support

### ISSUE THREAD

**Issue by getnamo** [getnamo/socketio-client-unreal#268]
Development work in https://github.com/getnamo/socketio-client-ue4/tree/ue5

Compiles with changes, but currently untested. Branched off of v1.6.0 master.

**Comment by getnamo** [comment]
Confirmed working on win64 
![image](https://user-images.githubusercontent.com/542365/119721323-e3338480-be1f-11eb-8672-22503f894380.png)

**Comment by getnamo** [comment]
Early release now available: https://github.com/getnamo/socketio-client-ue4/releases/tag/1.7.0

**Comment by MadlyFX** [comment]
Hey all! I'm using the UE5 version of the plugin, and it's disconnecting after about 10 seconds with a "SocketIO: SocketIO Disconnected _MTGTR3pvyBzP9sGAAAM reason: CLOSE_REASON_NORMAL"

This does not happen with the Unreal 4 version.

> 
> 
> Early release now available: https://github.com/getnamo/socketio-client-ue4/releases/tag/1.7.0

**Comment by getnamo** [comment]
1.7 version expects socket.io v3/v4 servers, that might be a cause

**Comment by MadlyFX** [comment]
I admit I don't have a way to check that (server is sio v2 in this case) but my experience in the past has been mismatching SIO versions simply don't talk at all. This feels more like a heartbeat is not going out.

**Comment by getnamo** [comment]
Test against a local server where you can control the version, if there is the same behavior then it points to another problem

**Comment by Rahul-learner** [comment]
How to add New C++  Class in unreal engine 5
I tried but it is not in    (File --> New C++ Class)

**Comment by getnamo** [comment]
It's moved to Tools tab in UE5
![image](https://user-images.githubusercontent.com/542365/126347615-8a4f68bf-6513-4dba-aee8-66b1f42ae1f3.png)

**Comment by Rahul-learner** [comment]
Thanks

**Comment by ltsfwrs** [comment]
Hey, anyone figured out how to make it work for the official Unreal Engine 5.0.0 release that just came out? Thanks!

**Comment by getnamo** [comment]
The yet branch of the plugin should compile correctly https://github.com/getnamo/socketio-client-ue4/tree/ue5. Otherwise I will make a new release shortly.

Only code changes for compile were
https://github.com/getnamo/socketio-client-ue4/commit/84279fd199a4ea77b2920718da6b36ddcd67b77e

**Comment by ltsfwrs** [comment]
![Socket](https://user-images.githubusercontent.com/93562278/162146718-c785f63e-e7bb-4079-b75a-a486b273b4d7.png)
I get this when I put it in the plugin folder of the project.

**Comment by getnamo** [comment]
UE5 production release build made. Available here: https://github.com/getnamo/socketio-client-unreal/releases/tag/v2.0.0.

**Comment by getnamo** [comment]
Closing due to release, if problem arises, open new issue with v2 plugin tag
