### ISSUE TITLE
socket.io component doesn't save

### ISSUE THREAD

**Issue by jdc711** [getnamo/socketio-client-unreal#277]
For some reason, after I shut off my computer and then turn it on and go back to Unreal project, the "socketIOclient" component that was previously attached to my actor is not there anymore, and I need to reattach a socketioclient component onto the actor and reattach some of the blueprint links. Do you know why this is happening? This is the error log:
Failed to load /Script/SocketIOClient.SocketIOClientComponent Referenced by K2Node_CallFunction_0
Failed to load /Script/SocketIOClient.SocketIOClientComponent Referenced by K2Node_VariableGet_1
Failed to load /Script/SocketIOClient.SocketIOClientComponent Referenced by K2Node_CallFunction_5
Failed to load /Script/SocketIOClient.SocketIOClientComponent Referenced by K2Node_VariableGet_3
Failed to load /Script/SocketIOClient.SocketIOClientComponent Referenced by K2Node_VariableGet_40
Failed to load /Script/SocketIOClient.SocketIOClientComponent Referenced by K2Node_CallFunction_12
Failed to load /Script/SocketIOClient.ESIOThreadOverrideOption Referenced by K2Node_CallFunction_12
Failed to load /Script/SocketIOClient.SocketIOClientComponent Referenced by SCS_Node_1

**Comment by getnamo** [comment]
Sounds like a broken blueprint, try re-saving or migrating the asset to fix it

**Comment by jdc711** [comment]
Which asset? The actor itself? Or the socketio component? Should I do this after I re-add the socketio commponent onto the actor?

**Comment by jdc711** [comment]
Even after I re save , once I close the editor and then reopen the project, the socketioclient component is gone. The node and connections are all still there; however, since the socketiocomponent no longer exists on the actor, the nodes break because it cant recognize the socketioclient target; thus I need to readd the component to the actor...

**Comment by getnamo** [comment]
Check that the parent actor file isnt read-only. Seems like your changes aren't holding. Check also you don't have two editors open at same time of the same project, this can sometimes stop saves

**Comment by jdc711** [comment]
How do I check if the parent actor file is not read only? I have been able to make other changes in blueprint, but for some reason only the socketio component doesnt stay on the actor.

**Comment by jdc711** [comment]
The changes only do not save when I completely close the entire unreal editor. If i just close the blueprint editor, then the socketiocomponent stays

**Comment by jdc711** [comment]
This is a very frustrating issue, as whenever I close unreal, I must recreate the componenet and then recreate/reconnect all the nodes+pins that involve the socketioclient component.

**Comment by getnamo** [comment]
It's not related to the plugin, your assets are broken. Remake the blueprint

**Comment by jdc711** [comment]
Ok. How can I remake the blueprint?

**Comment by jdc711** [comment]
you are right. It seems that variables I make do not save as well...

**Comment by jdc711** [comment]
I created a entirely new project, and this time I used the unreal built in plug in for socketioclient. Still, the socketiocomponent doesnt seem to save... does it maybe have something do with the c++ code overriding the blueprint for socketiocomponent?

**Comment by jdc711** [comment]
Huh! doing it in a blueprint-only project got rid of the problem! i wonder why that is...strange.. thanks for all your help

**Comment by getnamo** [comment]
I suspect something was holding a read-only hold on your blueprint files

**Comment by jdc711** [comment]
Do you know which file would be read only, and how would I change it to read and writeable? I attached the socket io component to the thirdpersoncharacter  , so maybe its that file?

**Comment by getnamo** [comment]
That would be my suspicion

**Comment by jdc711** [comment]
Do u know how I can change it to be writeable? Right now, I can still edit directly on blueprint, but I guess adding component part doesnt work

**Comment by BoraKim96** [comment]
Hi I have a same question, Did you solve this problem ?
