### ISSUE TITLE
Question about how socket.io works

### ISSUE THREAD

**Issue by jdc711** [getnamo/socketio-client-unreal#278]
I wanted to ask how the sockets and server/clients worked exactly. So, I was used to communication models where a client would connect to one socket and then communicate with a server binded to different socket. However, here, it seems that the server and unreal clients are all binding to the same host+port and comomunicating that way. Is my understanding of this wrong? 

say we specify the HOST and PORT for server in index.js as LOCALHOST and 8000. I assume the server will be running and listening to this socket for incoming messages. Does specifying the address and port in the socketioclient blueprint mean the socket that the ue4 client will attach to and use to send data?

**Comment by jdc711** [comment]
Maybe for some context about my project, I am trying to create a communication channel between two unreal 4 projects that are on separate machines far from each other. I want to use the server running on Node js as a backend to receive data from one client and send it to the other client. Thus, while I am currently using localhost, I want to get to where I can connect the server to a remote IP address and use this server to allow communication between 2 unreal projects on different computers. Any suggestions would be greatly appreciated. Thanks!!

**Comment by jdc711** [comment]
For the server, I am trying to run the node js on an AWS instance

**Comment by getnamo** [comment]
Socket.io is a protocol that typically lives on top of a websocket connection or in the old times over long polled http gets. The protocol is fairly simple and can be found here https://github.com/socketio/socket.io-protocol it

What socket.io provides above a normal websocket connection is auto-reconnect, binary interweaving in messages, namespaces, rooms (server side), and generally just an easier layer to deal with.

In terms of how it works, each connection is upgraded to a TCP connection and the server automatically can distinguish connections by unique IDs, so yes all clients do connect on the same port.

**Comment by jdc711** [comment]
I see, thanks so much for the explanation. So, technically, using this socket.io, should I be able to run the server code on a remote server and then connect with 2 distant ue4 clients?

**Comment by getnamo** [comment]
Yep, that's the entire purpose :)

**Comment by jdc711** [comment]
Right now, I am running the index.js server code on a AWS ec2 instance, and I replaced localhost:3000 in the socketiocomponent blueprint, however the unreal clients cannot connect to the server. When I try reaching the server through the browser, this works. Do you have any suggestions?

**Comment by getnamo** [comment]
Check socket.io version and ensure you're not using https, but http

**Comment by jdc711** [comment]
I am on socket.io 4.1.3? And how do I ensure http is being used? In index.js, there is this line which is:const io = require('socket.io')(http);

**Comment by getnamo** [comment]
If you're using 4.x+, ensure you're using plugin version v1.6 or newer.

**Comment by jdc711** [comment]
Ah, for the server version was too high, changing the server version to 2 did the trick. Thanks!

**Comment by jdc711** [comment]
Just curious, what port on the (local) computer does the ue4 client connect to?

**Comment by getnamo** [comment]
Whichever one you specify. The plugin defaults to 3000
