### ISSUE TITLE
Run Socket IO in Editor Blueprint

### ISSUE THREAD

**Issue by KarthikHebbarMN** [getnamo/socketio-client-unreal#285]
Hey,

I am trying to write a simple helper with my server being nodejs socket io.
 
I have created an Editor Utility Blueprint Actor and imported the SocketIO as a component. Noticed that the connection only worked in Playmode and not in Editor. 
Any configurations needed to be done or any enhancement/feature links I can look upon to achieve this? 

Thanks,
Karthik

**Comment by getnamo** [comment]
See https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SocketIOClient/Private/SocketIOClientComponent.cpp#L367 and bLimitConnectionToGameWorld on the https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SocketIOClient/Public/SocketIOClientComponent.h#L93

Generally speaking you may need to use your own wrapper for editor-only context see the FSocketIONative class https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SocketIOClient/Public/SocketIONative.h
