### ISSUE TITLE
"Invalid uri" on Linux Dedicated Server (running on VM issue)

### ISSUE THREAD

**Issue by Eresia** [getnamo/socketio-client-unreal#95]
Hello,

I'm trying to use the plugin to connect to a SocketIO server (with nodejs).
On Windows editor, no problem, it works.
On Windows Dedicated Server, same.
On Virtual Machines with Ubuntu 18/Debian 9/Debian 8 no problem too.

But when I try to test it on an hosted VPS (Test with OVH and 1&1) on Debian 8 or Ubuntu 18 I have this issue : 

```cpp
[2018-09-07 13:39:55] [application] Get Connection Error: invalid uri
[2018.09.07-13.39.55:430][  0]SocketIOLog: SocketIO failed to connect.
```

I tried many possible addresses (127.0.0.1, localhost, public address) and many formats (http://127.0.0.1:8080, https://127.0.0.1:8080, ws://127.0.0.1:8080, 127.0.0.1:8080, and the same without port and my server listens on port 80).

Have you any idea to fix this problem ?
Thanks !

**Comment by getnamo** [comment]
I haven't seen this before, what would be the minimal setup to replicate the bug?

Line points to callback here:: https://github.com/socketio/socket.io-client-cpp/blob/6063cb1d612f6ca0232d4134a018053fb8faea20/src/internal/sio_client_impl.cpp#L227

which points to somewhere here I think: https://github.com/zaphoyd/websocketpp/blob/c612a35f06138fad627c0ecf61f7b43d1328e32e/websocketpp/roles/client_endpoint.hpp#L89

NB: http**s** is currently not supported, make sure it's an http connection.

**Comment by Eresia** [comment]
Thanks for your answer.

Just try with an empty project with the plugin, add blueprint actor with the SocketIOClient component with default properties in a empty scene. Packaging and compile to Linux Server, send the server to VPS have the same error. 

I tested to clone and compile websocketpp and socket.io-client-cpp independently on the VPS and it works without problem. 

And I'm sure it's an http connexion.

**Comment by Eresia** [comment]
Tested today on a machine with Ubuntu 18 (Not a VM) and all works normally. So, the problem is only on external VPS...

**Comment by getnamo** [comment]
repull master and let me know if current plugin has the same issue on VMs

**Comment by getnamo** [comment]
Closing due to age, re-open if problem persists in new plugin versions.
